-- ========== 消费规则表：合并 1.csv（高优）与 2.csv（兜底） ==========
-- 说明：
--   - 所有复合 pattern 已拆分为单条
--   - 无重复规则（按 id 和 pattern 去重）
--   - 优先级：85~95（具体） > 110（通用）

INSERT INTO `consume_rule` 
(`id`, `categoryId`, `pattern`, `patternType`, `priority`, `active`, `remark`, `createTime`)
VALUES

-- 💰 收入类（通常无需规则，但可捕获退款/补贴）
('rule_inc_alipay_refund', 'REIMB-03', '支付宝退款', 'contains', 90, 1, '支付宝退款自动归为返还', NOW()),
('rule_inc_wechat_refund', 'REIMB-03', '微信支付退款', 'contains', 90, 1, '微信退款', NOW()),

-- 🏠 固定支出
('rule_fixed_water_electric_1', 'FIXED-03', '水费', 'regex', 95, 1, '水电燃气', NOW()),
('rule_fixed_water_electric_2', 'FIXED-03', '电费', 'regex', 95, 1, '水电燃气', NOW()),
('rule_fixed_water_electric_3', 'FIXED-03', '燃气费', 'regex', 95, 1, '水电燃气', NOW()),
('rule_fixed_property', 'FIXED-02', '物业费', 'contains', 95, 1, '物业费', NOW()),
('rule_fixed_property_2', 'FIXED-02', '物业管理', 'contains', 95, 1, '物业费', NOW()),
('rule_fixed_net_1', 'FIXED-04', '宽带费', 'contains', 95, 1, '宽带/网络', NOW()),
('rule_fixed_net_2', 'FIXED-04', '网络服务', 'contains', 95, 1, '宽带/网络', NOW()),
('rule_fixed_net_3', 'FIXED-04', '电信', 'contains', 95, 1, '宽带/网络', NOW()),
('rule_fixed_net_4', 'FIXED-04', '联通', 'contains', 95, 1, '宽带/网络', NOW()),
('rule_fixed_net_5', 'FIXED-04', '移动(宽带)', 'contains', 95, 1, '宽带/网络', NOW()),
('rule_fixed_phone_1', 'FIXED-05', '话费', 'contains', 95, 1, '手机话费', NOW()),
('rule_fixed_phone_2', 'FIXED-05', '通信套餐', 'contains', 95, 1, '手机话费', NOW()),
('rule_fixed_phone_3', 'FIXED-05', '月租', 'contains', 95, 1, '手机话费', NOW()),
('rule_fixed_insurance_life_1', 'FIXED-06', '寿险', 'contains', 90, 1, '保险费', NOW()),
('rule_fixed_insurance_life_2', 'FIXED-06', '重疾险', 'contains', 90, 1, '保险费', NOW()),
('rule_fixed_insurance_life_3', 'FIXED-06', '医疗险', 'contains', 90, 1, '保险费', NOW()),
('rule_fixed_insurance_life_4', 'FIXED-06', '车险', 'contains', 90, 1, '保险费', NOW()),
('rule_fixed_subscription_video_1', 'FIXED-07', '爱奇艺', 'contains', 90, 1, '视频会员', NOW()),
('rule_fixed_subscription_video_2', 'FIXED-07', '腾讯视频', 'contains', 90, 1, '视频会员', NOW()),
('rule_fixed_subscription_video_3', 'FIXED-07', '优酷', 'contains', 90, 1, '视频会员', NOW()),
('rule_fixed_subscription_video_4', 'FIXED-07', '芒果TV', 'contains', 90, 1, '视频会员', NOW()),
('rule_fixed_subscription_video_5', 'FIXED-07', '哔哩哔哩大会员', 'contains', 90, 1, '视频会员', NOW()),
('rule_fixed_subscription_music_1', 'FIXED-07', '网易云音乐', 'contains', 90, 1, '音乐会员', NOW()),
('rule_fixed_subscription_music_2', 'FIXED-07', 'QQ音乐', 'contains', 90, 1, '音乐会员', NOW()),
('rule_fixed_subscription_music_3', 'FIXED-07', '酷狗', 'contains', 90, 1, '音乐会员', NOW()),
('rule_fixed_subscription_music_4', 'FIXED-07', '酷我', 'contains', 90, 1, '音乐会员', NOW()),
('rule_fixed_subscription_cloud_1', 'FIXED-07', '阿里云盘', 'contains', 90, 1, '云盘订阅', NOW()),
('rule_fixed_subscription_cloud_2', 'FIXED-07', '百度网盘', 'contains', 90, 1, '云盘订阅', NOW()),
('rule_fixed_subscription_cloud_3', 'FIXED-07', 'iCloud', 'contains', 90, 1, '云盘订阅', NOW()),
('rule_fixed_subscription_cloud_4', 'FIXED-07', 'OneDrive', 'contains', 90, 1, '云盘订阅', NOW()),
('rule_fixed_subscription_software_1', 'FIXED-07', 'WPS', 'contains', 90, 1, '软件订阅', NOW()),
('rule_fixed_subscription_software_2', 'FIXED-07', 'Office 365', 'contains', 90, 1, '软件订阅', NOW()),
('rule_fixed_subscription_software_3', 'FIXED-07', 'Adobe', 'contains', 90, 1, '软件订阅', NOW()),

-- 🛒 日常生活 - 餐饮
('rule_living_meituan', 'LIVING-01', '美团', 'contains', 85, 1, '美团外卖/团购', NOW()),
('rule_living_eleme', 'LIVING-01', '饿了么', 'contains', 85, 1, '饿了么外卖', NOW()),
('rule_living_starbucks', 'LIVING-01', '星巴克', 'contains', 90, 1, '星巴克', NOW()),
('rule_living_kfc_mcdonalds_1', 'LIVING-01', '肯德基', 'contains', 90, 1, '快餐', NOW()),
('rule_living_kfc_mcdonalds_2', 'LIVING-01', '麦当劳', 'contains', 90, 1, '快餐', NOW()),
('rule_living_kfc_mcdonalds_3', 'LIVING-01', '必胜客', 'contains', 90, 1, '快餐', NOW()),
('rule_living_coffee_1', 'LIVING-01', '瑞幸', 'contains', 90, 1, '咖啡品牌', NOW()),
('rule_living_coffee_2', 'LIVING-01', '库迪', 'contains', 90, 1, '咖啡品牌', NOW()),
('rule_living_coffee_3', 'LIVING-01', 'Manner', 'contains', 90, 1, '咖啡品牌', NOW()),
('rule_living_coffee_4', 'LIVING-01', 'Seesaw', 'contains', 90, 1, '咖啡品牌', NOW()),
('rule_living_supermarket_1', 'LIVING-02', '永辉', 'contains', 90, 1, '大型超市', NOW()),
('rule_living_supermarket_2', 'LIVING-02', '华润万家', 'contains', 90, 1, '大型超市', NOW()),
('rule_living_supermarket_3', 'LIVING-02', '盒马', 'contains', 90, 1, '大型超市', NOW()),
('rule_living_supermarket_4', 'LIVING-02', '大润发', 'contains', 90, 1, '大型超市', NOW()),
('rule_living_supermarket_5', 'LIVING-02', '沃尔玛', 'contains', 90, 1, '大型超市', NOW()),
('rule_living_supermarket_6', 'LIVING-02', '家乐福', 'contains', 90, 1, '大型超市', NOW()),
('rule_living_supermarket_7', 'LIVING-02', '物美', 'contains', 90, 1, '大型超市', NOW()),
('rule_living_convenience_1', 'LIVING-02', '7-Eleven', 'contains', 90, 1, '便利店', NOW()),
('rule_living_convenience_2', 'LIVING-02', '全家', 'contains', 90, 1, '便利店', NOW()),
('rule_living_convenience_3', 'LIVING-02', '罗森', 'contains', 90, 1, '便利店', NOW()),
('rule_living_convenience_4', 'LIVING-02', '便利蜂', 'contains', 90, 1, '便利店', NOW()),

-- 🚇 公共交通 & 网约车
('rule_living_subway_bus_1', 'LIVING-04', '地铁', 'contains', 90, 1, '公共交通', NOW()),
('rule_living_subway_bus_2', 'LIVING-04', '公交', 'contains', 90, 1, '公共交通', NOW()),
('rule_living_subway_bus_3', 'LIVING-04', '一卡通', 'contains', 90, 1, '公共交通', NOW()),
('rule_living_subway_bus_4', 'LIVING-04', '乘车码', 'contains', 90, 1, '公共交通', NOW()),
('rule_living_didi_1', 'LIVING-05', '滴滴出行', 'contains', 90, 1, '滴滴打车', NOW()),
('rule_living_didi_2', 'LIVING-05', '滴滴快车', 'contains', 90, 1, '滴滴打车', NOW()),
('rule_living_didi_3', 'LIVING-05', '滴滴专车', 'contains', 90, 1, '滴滴打车', NOW()),
('rule_living_gaode_tencent_1', 'LIVING-05', '高德打车', 'contains', 90, 1, '聚合打车平台', NOW()),
('rule_living_gaode_tencent_2', 'LIVING-05', '腾讯出行', 'contains', 90, 1, '聚合打车平台', NOW()),
('rule_living_hellobike_1', 'LIVING-04', '哈啰出行', 'contains', 90, 1, '共享单车', NOW()),
('rule_living_hellobike_2', 'LIVING-04', '青桔单车', 'contains', 90, 1, '共享单车', NOW()),
('rule_living_hellobike_3', 'LIVING-04', '美团单车', 'contains', 90, 1, '共享单车', NOW()),

-- 🏥 医疗健康
('rule_living_drugstore_1', 'LIVING-06', '同仁堂', 'contains', 90, 1, '药店', NOW()),
('rule_living_drugstore_2', 'LIVING-06', '老百姓大药房', 'contains', 90, 1, '药店', NOW()),
('rule_living_drugstore_3', 'LIVING-06', '益丰大药房', 'contains', 90, 1, '药店', NOW()),
('rule_living_drugstore_4', 'LIVING-06', '叮当快药', 'contains', 90, 1, '药店', NOW()),
('rule_living_hospital_1', 'LIVING-06', '医院', 'contains', 85, 1, '基础医疗', NOW()),
('rule_living_hospital_2', 'LIVING-06', '门诊', 'contains', 85, 1, '基础医疗', NOW()),
('rule_living_hospital_3', 'LIVING-06', '体检中心', 'contains', 85, 1, '基础医疗', NOW()),
('rule_living_dental_1', 'LIVING-10', '口腔', 'contains', 90, 1, '专项牙科', NOW()),
('rule_living_dental_2', 'LIVING-10', '牙科', 'contains', 90, 1, '专项牙科', NOW()),
('rule_living_dental_3', 'LIVING-10', '种植牙', 'contains', 90, 1, '专项牙科', NOW()),
('rule_living_dental_4', 'LIVING-10', '正畸', 'contains', 90, 1, '专项牙科', NOW()),
('rule_living_eye_1', 'LIVING-10', '眼科', 'contains', 90, 1, '眼科专项', NOW()),
('rule_living_eye_2', 'LIVING-10', '配镜', 'contains', 90, 1, '眼科专项', NOW()),
('rule_living_eye_3', 'LIVING-10', '近视手术', 'contains', 90, 1, '眼科专项', NOW()),

-- 📦 快递物流
('rule_living_express_1', 'LIVING-07', '顺丰', 'contains', 90, 1, '快递费', NOW()),
('rule_living_express_2', 'LIVING-07', '中通', 'contains', 90, 1, '快递费', NOW()),
('rule_living_express_3', 'LIVING-07', '圆通', 'contains', 90, 1, '快递费', NOW()),
('rule_living_express_4', 'LIVING-07', '申通', 'contains', 90, 1, '快递费', NOW()),
('rule_living_express_5', 'LIVING-07', '韵达', 'contains', 90, 1, '快递费', NOW()),
('rule_living_express_6', 'LIVING-07', '京东物流', 'contains', 90, 1, '快递费', NOW()),
('rule_living_express_7', 'LIVING-07', '菜鸟裹裹', 'contains', 90, 1, '快递费', NOW()),
('rule_living_fresh_1', 'LIVING-02', '每日优鲜', 'contains', 90, 1, '生鲜电商', NOW()),
('rule_living_fresh_2', 'LIVING-02', '叮咚买菜', 'contains', 90, 1, '生鲜电商', NOW()),
('rule_living_fresh_3', 'LIVING-02', '朴朴超市', 'contains', 90, 1, '生鲜电商', NOW()),

-- 🛍️ 购物与耐用品
('rule_shopping_taobao_1', 'SHOPPING-01', '淘宝', 'contains', 85, 1, '服饰鞋帽（电商）', NOW()),
('rule_shopping_taobao_2', 'SHOPPING-01', '天猫', 'contains', 85, 1, '服饰鞋帽（电商）', NOW()),
('rule_shopping_jd', 'SHOPPING-03', '京东', 'contains', 85, 1, '电子产品（京东）', NOW()),
('rule_shopping_pinduoduo', 'SHOPPING-01', '拼多多', 'contains', 85, 1, '低价商品', NOW()),
('rule_shopping_suning', 'SHOPPING-04', '苏宁易购', 'contains', 90, 1, '家电', NOW()),
('rule_shopping_xiaomi_1', 'SHOPPING-03', '小米', 'contains', 90, 1, '数码品牌', NOW()),
('rule_shopping_xiaomi_2', 'SHOPPING-03', '华为', 'contains', 90, 1, '数码品牌', NOW()),
('rule_shopping_xiaomi_3', 'SHOPPING-03', 'Apple', 'contains', 90, 1, '数码品牌', NOW()),
('rule_shopping_xiaomi_4', 'SHOPPING-03', '苹果', 'contains', 90, 1, '数码品牌', NOW()),
('rule_shopping_sports_1', 'SHOPPING-07', '耐克', 'contains', 90, 1, '体育用品', NOW()),
('rule_shopping_sports_2', 'SHOPPING-07', '阿迪达斯', 'contains', 90, 1, '体育用品', NOW()),
('rule_shopping_sports_3', 'SHOPPING-07', '李宁', 'contains', 90, 1, '体育用品', NOW()),
('rule_shopping_sports_4', 'SHOPPING-07', '安踏', 'contains', 90, 1, '体育用品', NOW()),
('rule_shopping_sports_5', 'SHOPPING-07', 'Keep', 'contains', 90, 1, '体育用品', NOW()),
('rule_shopping_sports_6', 'SHOPPING-07', '迪卡侬', 'contains', 90, 1, '体育用品', NOW()),
('rule_shopping_cosmetics_1', 'SHOPPING-02', '兰蔻', 'contains', 90, 1, '化妆品', NOW()),
('rule_shopping_cosmetics_2', 'SHOPPING-02', '雅诗兰黛', 'contains', 90, 1, '化妆品', NOW()),
('rule_shopping_cosmetics_3', 'SHOPPING-02', '欧莱雅', 'contains', 90, 1, '化妆品', NOW()),
('rule_shopping_cosmetics_4', 'SHOPPING-02', '完美日记', 'contains', 90, 1, '化妆品', NOW()),
('rule_shopping_cosmetics_5', 'SHOPPING-02', '花西子', 'contains', 90, 1, '化妆品', NOW()),
('rule_shopping_mother_1', 'SHOPPING-09', '孩子王', 'contains', 90, 1, '母婴用品', NOW()),
('rule_shopping_mother_2', 'SHOPPING-09', '爱婴室', 'contains', 90, 1, '母婴用品', NOW()),
('rule_shopping_mother_3', 'SHOPPING-09', '贝亲', 'contains', 90, 1, '母婴用品', NOW()),
('rule_shopping_mother_4', 'SHOPPING-09', '帮宝适', 'contains', 90, 1, '母婴用品', NOW()),

-- 📚 教育培训
('rule_edu_youdao_1', 'EDU-04', '有道精品课', 'contains', 90, 1, '在线课程', NOW()),
('rule_edu_youdao_2', 'EDU-04', '网易云课堂', 'contains', 90, 1, '在线课程', NOW()),
('rule_edu_xueersi_1', 'EDU-00', '学而思', 'contains', 90, 1, 'K12/留学培训', NOW()),
('rule_edu_xueersi_2', 'EDU-00', '新东方', 'contains', 90, 1, 'K12/留学培训', NOW()),
('rule_edu_chinaedu_1', 'EDU-00', '中国大学MOOC', 'contains', 90, 1, '学历教育平台', NOW()),
('rule_edu_chinaedu_2', 'EDU-00', '学堂在线', 'contains', 90, 1, '学历教育平台', NOW()),
('rule_edu_exam_1', 'EDU-03', '报名费', 'contains', 90, 1, '考证费用', NOW()),
('rule_edu_exam_2', 'EDU-03', '考试费', 'contains', 90, 1, '考证费用', NOW()),
('rule_edu_exam_3', 'EDU-03', '职称评审', 'contains', 90, 1, '考证费用', NOW()),

-- 🎡 娱乐与旅行
('rule_ent_maoyan_1', 'ENT-01', '猫眼', 'contains', 90, 1, '电影购票', NOW()),
('rule_ent_maoyan_2', 'ENT-01', '淘票票', 'contains', 90, 1, '电影购票', NOW()),
('rule_ent_cinema_1', 'ENT-01', '万达影城', 'contains', 90, 1, '影院名称', NOW()),
('rule_ent_cinema_2', 'ENT-01', 'CGV', 'contains', 90, 1, '影院名称', NOW()),
('rule_ent_cinema_3', 'ENT-01', 'UME', 'contains', 90, 1, '影院名称', NOW()),
('rule_ent_cinema_4', 'ENT-01', '奥斯卡', 'contains', 90, 1, '影院名称', NOW()),
('rule_ent_travel_ctrip_1', 'ENT-02', '携程', 'contains', 90, 1, '旅游平台', NOW()),
('rule_ent_travel_ctrip_2', 'ENT-02', '去哪儿', 'contains', 90, 1, '旅游平台', NOW()),
('rule_ent_travel_ctrip_3', 'ENT-02', '飞猪', 'contains', 90, 1, '旅游平台', NOW()),
('rule_ent_travel_ctrip_4', 'ENT-02', '同程', 'contains', 90, 1, '旅游平台', NOW()),
('rule_ent_hotel_1', 'ENT-02', '如家', 'contains', 90, 1, '酒店品牌', NOW()),
('rule_ent_hotel_2', 'ENT-02', '汉庭', 'contains', 90, 1, '酒店品牌', NOW()),
('rule_ent_hotel_3', 'ENT-02', '全季', 'contains', 90, 1, '酒店品牌', NOW()),
('rule_ent_hotel_4', 'ENT-02', '亚朵', 'contains', 90, 1, '酒店品牌', NOW()),
('rule_ent_hotel_5', 'ENT-02', '希尔顿', 'contains', 90, 1, '酒店品牌', NOW()),
('rule_ent_gym_1', 'ENT-03', '超级猩猩', 'contains', 90, 1, '健身房', NOW()),
('rule_ent_gym_2', 'ENT-03', '乐刻', 'contains', 90, 1, '健身房', NOW()),
('rule_ent_gym_3', 'ENT-03', '威尔士', 'contains', 90, 1, '健身房', NOW()),
('rule_ent_gym_4', 'ENT-03', '健身', 'contains', 90, 1, '健身房', NOW()),
('rule_ent_beauty_1', 'ENT-04', '美容院', 'contains', 90, 1, '个人护理服务', NOW()),
('rule_ent_beauty_2', 'ENT-04', '美发', 'contains', 90, 1, '个人护理服务', NOW()),
('rule_ent_beauty_3', 'ENT-04', '理发', 'contains', 90, 1, '个人护理服务', NOW()),
('rule_ent_beauty_4', 'ENT-04', '按摩', 'contains', 90, 1, '个人护理服务', NOW()),
('rule_ent_beauty_5', 'ENT-04', 'SPA', 'contains', 90, 1, '个人护理服务', NOW()),
('rule_ent_beauty_6', 'ENT-04', '理疗', 'contains', 90, 1, '个人护理服务', NOW()),
('rule_ent_game_1', 'ENT-06', '王者荣耀', 'contains', 90, 1, '游戏充值', NOW()),
('rule_ent_game_2', 'ENT-06', '原神', 'contains', 90, 1, '游戏充值', NOW()),
('rule_ent_game_3', 'ENT-06', 'Steam', 'contains', 90, 1, '游戏充值', NOW()),
('rule_ent_game_4', 'ENT-06', 'Apple充值', 'contains', 90, 1, '游戏充值', NOW()),

-- 💳 金融服务
('rule_fin_alipay_transfer', 'FIN-08', '转账-到', 'contains', 95, 1, '支付宝转账', NOW()),
('rule_fin_wechat_transfer', 'FIN-08', '微信转账', 'contains', 95, 1, '微信转账', NOW()),
('rule_fin_bank_fee_1', 'FIN-01', '手续费', 'contains', 90, 1, '银行手续费', NOW()),
('rule_fin_bank_fee_2', 'FIN-01', '账户管理费', 'contains', 90, 1, '银行手续费', NOW()),
('rule_fin_bank_fee_3', 'FIN-01', '短信通知费', 'contains', 90, 1, '银行手续费', NOW()),
('rule_fin_credit_interest_1', 'FIN-04', '信用卡利息', 'contains', 90, 1, '信用卡费用', NOW()),
('rule_fin_credit_interest_2', 'FIN-04', '违约金', 'contains', 90, 1, '信用卡费用', NOW()),
('rule_fin_credit_interest_3', 'FIN-04', '年费', 'contains', 90, 1, '信用卡费用', NOW()),
('rule_fin_loan_interest_1', 'FIN-05', '贷款利息', 'contains', 90, 1, '贷款利息', NOW()),
('rule_fin_loan_interest_2', 'FIN-05', '房贷还款', 'contains', 90, 1, '贷款利息', NOW()),
('rule_fin_loan_interest_3', 'FIN-05', '信用贷', 'contains', 90, 1, '贷款利息', NOW()),
('rule_fin_withdrawal_1', 'FIN-06', 'ATM取现', 'contains', 90, 1, '取现手续费', NOW()),
('rule_fin_withdrawal_2', 'FIN-06', '信用卡取现', 'contains', 90, 1, '取现手续费', NOW()),
('rule_fin_alipay_withdraw', 'FIN-07', '支付宝提现', 'contains', 90, 1, '支付平台提现费', NOW()),

-- 🤝 人情与公益
('rule_social_redpacket_out_1', 'SOCIAL-01', '微信红包', 'contains', 90, 1, '发出红包', NOW()),
('rule_social_redpacket_out_2', 'SOCIAL-01', '转账给', 'contains', 90, 1, '发出红包', NOW()),
('rule_social_gift_1', 'SOCIAL-02', '礼品', 'contains', 90, 1, '礼物购买', NOW()),
('rule_social_gift_2', 'SOCIAL-02', '鲜花', 'contains', 90, 1, '礼物购买', NOW()),
('rule_social_gift_3', 'SOCIAL-02', '蛋糕', 'contains', 90, 1, '礼物购买', NOW()),
('rule_social_gift_4', 'SOCIAL-02', '周大福', 'contains', 90, 1, '礼物购买', NOW()),
('rule_social_gift_5', 'SOCIAL-02', 'DR钻戒', 'contains', 90, 1, '礼物购买', NOW()),
('rule_social_charity_1', 'SOCIAL-04', '腾讯公益', 'contains', 90, 1, '公益捐款', NOW()),
('rule_social_charity_2', 'SOCIAL-04', '支付宝公益', 'contains', 90, 1, '公益捐款', NOW()),
('rule_social_charity_3', 'SOCIAL-04', '水滴筹', 'contains', 90, 1, '公益捐款', NOW()),
('rule_social_charity_4', 'SOCIAL-04', '轻松筹', 'contains', 90, 1, '公益捐款', NOW()),

-- 🚗 交通出行
('rule_transport_12306_1', 'TRANSPORT-07', '12306', 'contains', 90, 1, '火车票', NOW()),
('rule_transport_12306_2', 'TRANSPORT-07', '铁路订票', 'contains', 90, 1, '火车票', NOW()),
('rule_transport_airline_1', 'TRANSPORT-07', '中国国航', 'contains', 90, 1, '航空出行', NOW()),
('rule_transport_airline_2', 'TRANSPORT-07', '南方航空', 'contains', 90, 1, '航空出行', NOW()),
('rule_transport_airline_3', 'TRANSPORT-07', '东方航空', 'contains', 90, 1, '航空出行', NOW()),
('rule_transport_airline_4', 'TRANSPORT-07', '海南航空', 'contains', 90, 1, '航空出行', NOW()),
('rule_transport_airline_5', 'TRANSPORT-07', '机票', 'contains', 90, 1, '航空出行', NOW()),
('rule_transport_gas_1', 'TRANSPORT-01', '中石化', 'contains', 90, 1, '加油/充电', NOW()),
('rule_transport_gas_2', 'TRANSPORT-01', '中石油', 'contains', 90, 1, '加油/充电', NOW()),
('rule_transport_gas_3', 'TRANSPORT-01', '壳牌', 'contains', 90, 1, '加油/充电', NOW()),
('rule_transport_gas_4', 'TRANSPORT-01', '充电服务', 'contains', 90, 1, '加油/充电', NOW()),
('rule_transport_parking_1', 'TRANSPORT-02', '停车费', 'contains', 90, 1, '停车', NOW()),
('rule_transport_parking_2', 'TRANSPORT-02', '停车场', 'contains', 90, 1, '停车', NOW()),
('rule_transport_parking_3', 'TRANSPORT-02', 'ETCP', 'contains', 90, 1, '停车', NOW()),
('rule_transport_toll_1', 'TRANSPORT-03', '高速收费', 'contains', 90, 1, '路桥费', NOW()),
('rule_transport_toll_2', 'TRANSPORT-03', '过路费', 'contains', 90, 1, '路桥费', NOW()),
('rule_transport_toll_3', 'TRANSPORT-03', '过桥费', 'contains', 90, 1, '路桥费', NOW()),
('rule_transport_car_maintain_1', 'TRANSPORT-04', '汽车维修', 'contains', 90, 1, '车辆维护', NOW()),
('rule_transport_car_maintain_2', 'TRANSPORT-04', '保养', 'contains', 90, 1, '车辆维护', NOW()),
('rule_transport_car_maintain_3', 'TRANSPORT-04', '洗车', 'contains', 90, 1, '车辆维护', NOW()),
('rule_transport_rental_1', 'TRANSPORT-06', '神州租车', 'contains', 90, 1, '租车/代驾', NOW()),
('rule_transport_rental_2', 'TRANSPORT-06', '一嗨租车', 'contains', 90, 1, '租车/代驾', NOW()),
('rule_transport_rental_3', 'TRANSPORT-06', '代驾', 'contains', 90, 1, '租车/代驾', NOW()),
('rule_transport_violation_1', 'TRANSPORT-08', '交通罚款', 'contains', 90, 1, '交通违章', NOW()),
('rule_transport_violation_2', 'TRANSPORT-08', '违章缴费', 'contains', 90, 1, '交通违章', NOW()),

-- 🔄 报销与返还
('rule_reimb_company_1', 'REIMB-01', '餐补', 'contains', 90, 1, '公司补贴', NOW()),
('rule_reimb_company_2', 'REIMB-01', '交通补贴', 'contains', 90, 1, '公司补贴', NOW()),
('rule_reimb_company_3', 'REIMB-01', '通讯补贴', 'contains', 90, 1, '公司补贴', NOW()),
('rule_reimb_travel_1', 'REIMB-02', '差旅报销', 'contains', 90, 1, '差旅费', NOW()),
('rule_reimb_travel_2', 'REIMB-02', '住宿报销', 'contains', 90, 1, '差旅费', NOW());
